engines:
  eslint:
    enabled: true
    channel: 'eslint-2'
  duplication:
    enabled: true
    config:
      languages:
        - javascript
ratings:
  paths:
    - src/**
exclude_paths:
  - tests/**/*
